# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='teaser',
            field=models.CharField(default='images.jpg', max_length=255),
            preserve_default=False,
        ),
    ]
